apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohit-deploy
spec:
  selector:
    matchLabels:
      app: banana
  replicas: 2
  template:
    metadata:
      labels:
        app: banana
    spec:
      containers:
       - name: banana-app
         image: hashicorp/http-echo
         args:
           - "-text=banana"
